# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # make vm 
    config.vm.define "vm-docker" do |node|
      node.vm.box = "centos/7"
      node.vm.box_check_update = false
      node.vm.hostname = "vm-docker"
      node.vm.network "public_network", ip: "172.20.10.115"
      node.vm.provision "shell", path: "setup-docker.sh"   
    end
    
  end