# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # make vm 
    config.vm.define "vm-template" do |node|
      node.vm.box = "generic/centos7"
      node.vm.box_check_update = false
      #node.vbguest.auto_update = false
      node.vm.hostname = "vm-template"
      node.vm.network "public_network", ip: "172.20.10.115"
      #node.vm.network "private_network", ip: "172.16.10.100"
      #node.vm.provision "shell", path: "setup-master.sh"   
    end
    
  end